r"""

from .ma_lists_bots import *

find:
# from ma_lists\.[^ ]+ import
replace:
# from .ma_lists_bots import

"""

from ma_lists import N_cit_ies_s_lower, Jobs_key_mens, Jobs_key_womens, womens_Jobs_2017, Female_Jobs, Men_Womens_Jobs, Nat_Before_Occ, Men_Womens_with_nato, Jobs_new, Jobs_key, New_P17_Finall, All_Nat, Nat_women, All_contry_ar, All_contry_with_nat, All_contry_with_nat_keys_is_en, All_contry_with_nat_ar, contries_from_nat, Nat_mens, Nat_Womens, Nat_men, ar_Nat_men, nats_to_add, fanco_line, Sports_Keys_For_Team, Sports_Keys_For_Label, Sports_Keys_For_Jobs, pf_keys2, pop_of_without_in, pop_of_football_lower, Word_After_Years, summer_winter_games, typeTable_7, albums_type, film_production_company, NN_table, Ambassadors_tab, Inter_Feds_lower, Clubs_key_2, By_table, By_orginal2, By_table_orginal, Music_By_table, Films_TT, typeTable_4, Films_key_CAO, Films_key_For_nat, Films_key_CAO_new_format, television_keys_female, Films_key_333, Films_key_man, film_key_women_2, films_mslslat_tab, film_Keys_For_female, Films_keys_both_new, religious_keys_PP, Add_in_table2, Parties, languages_pop, lang_ttty, languages_key, lang_key_m, New_female_keys, New_male_keys, New_Company, military_format_women_without_al_from_end, military_format_women_without_al, military_format_women, military_format_men, ministrs_tab_for_pop_format, change_numb_to_word, People_key, pop_All_2018, Teams_new, sport_formts_en_ar_is_p17, sport_formts_en_p17_ar_nat, sport_formts_for_p17, nat_p17_oioi, en_is_nat_ar_is_P17, en_is_nat_ar_is_al_mens, en_is_nat_ar_is_man, en_is_nat_ar_is_al_women, en_is_nat_ar_is_women, change_male_to_female, priffix_lab_for_2018, Main_priffix, Main_priffix_to, Multi_sport_for_Jobs, en_is_nat_ar_is_women_2, en_is_P17_ar_is_mens, en_is_P17_ar_is_P17, replace_labels_2022, Mens_suffix, Mens_priffix, Women_s_priffix, en_is_P17_ar_is_al_women, US_State_lower, kk_end_US_State, party_end_keys

__all__ = [
    "N_cit_ies_s_lower",
    #
    "Jobs_key_mens",
    "Jobs_key_womens",
    "womens_Jobs_2017",
    "Female_Jobs",
    "Men_Womens_Jobs",
    "Nat_Before_Occ",
    "Men_Womens_with_nato",
    "Jobs_new",
    "Jobs_key",
    #
    "New_P17_Finall",
    "All_Nat",
    "Nat_women",
    "All_contry_ar",
    "All_contry_with_nat",
    "All_contry_with_nat_keys_is_en",
    "All_contry_with_nat_ar",
    "contries_from_nat",
    "Nat_mens",
    "Nat_Womens",
    "Nat_men",
    "ar_Nat_men",
    "nats_to_add",
    #
    "fanco_line",
    "Sports_Keys_For_Team",
    "Sports_Keys_For_Label",
    "Sports_Keys_For_Jobs",
    #
    "pf_keys2",
    "pop_of_without_in",
    "pop_of_football_lower",
    "Word_After_Years",
    #
    "typeTable_7",
    "albums_type",
    "film_production_company",
    "NN_table",
    "Ambassadors_tab",
    "summer_winter_games",
    #
    "Inter_Feds_lower",
    #
    "Clubs_key_2",
    #
    "By_table",
    "By_orginal2",
    "By_table_orginal",
    "Music_By_table",
    #
    "Films_TT",
    "typeTable_4",
    "Films_key_CAO",
    "Films_key_For_nat",
    "Films_key_CAO_new_format",
    "television_keys_female",
    "Films_key_man",
    "film_key_women_2",
    "films_mslslat_tab",
    "film_Keys_For_female",
    "Films_keys_both_new",
    "Films_key_333",
    #
    "religious_keys_PP",
    #
    "Add_in_table2",
    "Parties",
    #
    "languages_pop",
    "lang_ttty",
    "languages_key",
    "lang_key_m",
    #
    "New_female_keys",
    "New_male_keys",
    "New_Company",
    #
    "military_format_women_without_al_from_end",
    "military_format_women_without_al",
    "military_format_women",
    "military_format_men",
    #
    "ministrs_tab_for_pop_format",
    #
    "change_numb_to_word",
    #
    "People_key",
    #
    "pop_All_2018",
    #
    "Teams_new",
    "sport_formts_en_ar_is_p17",
    "sport_formts_en_p17_ar_nat",
    #
    "sport_formts_for_p17",
    "nat_p17_oioi",
    #
    "en_is_nat_ar_is_P17",
    "en_is_nat_ar_is_al_mens",
    "en_is_nat_ar_is_man",
    "en_is_nat_ar_is_al_women",
    "en_is_nat_ar_is_women",
    "change_male_to_female",
    "priffix_lab_for_2018",
    "Main_priffix",
    "Main_priffix_to",
    "Multi_sport_for_Jobs",
    "en_is_nat_ar_is_women_2",
    "en_is_P17_ar_is_mens",
    "en_is_P17_ar_is_al_women",
    "en_is_P17_ar_is_P17",
    "replace_labels_2022",
    "Mens_suffix",
    "Mens_priffix",
    "Women_s_priffix",
    #
    "US_State_lower",
    "kk_end_US_State",
    "party_end_keys",
    #
]
