
OIUHNM2 = {
    "Category:Egyptian male sport shooters": "تصنيف:لاعبو رماية ذكور مصريون",
    "Category:Female association football managers": "تصنيف:مديرات كرة قدم",
    "Category:Military organization by country": "تصنيف:منظمات عسكرية حسب البلد",
    "Category:2000s in film": "تصنيف:عقد 2000 في الأفلام",
    "Category:Animals by year of formal description": "تصنيف:حيوانات حسب سنة الوصف",
    "Category:1994–95 in European rugby union by country": "تصنيف:اتحاد الرجبي الأوروبي في 1994–95 حسب البلد",
    "Category:Olympic shooters of Egypt": "تصنيف:رماة أولمبيون من مصر",
    "Category:Peruvian documentary film directors": "تصنيف:مخرجو أفلام وثائقية بيروفيون",
    "Category:Books about automobiles": "تصنيف:كتب عن سيارات",
    "Category:Participants in British reality television series": "تصنيف:مشاركون في مسلسلات تلفزيونية واقعية بريطانية",
    "Category:21st-century films": "تصنيف:أفلام القرن 21",
    "Category:Tetrapods by century of formal description": "تصنيف:رباعيات أطراف حسب قرن الوصف",
    "Category:Women's universities and colleges in India": "تصنيف:جامعات وكليات نسائية في الهند",
    "Category:Songs about automobiles": "تصنيف:أغاني عن سيارات",
    "Category:Disney animated films": "تصنيف:أفلام ديزني رسوم متحركة",
    "Category:2000s in American cinema": "تصنيف:السينما الأمريكية في عقد 2000",
    "Category:documentary filmmakers by nationality": "تصنيف:صانعو أفلام وثائقية حسب الجنسية",
    "Category:Works about automobiles": "تصنيف:أعمال عن سيارات",
    "Category:Films about automobiles": "تصنيف:أفلام عن سيارات",
    "Category:yemeni war filmmakers": "تصنيف:صانعو أفلام حربية يمنيون",
    "Category:Egyptian female sport shooters": "تصنيف:لاعبات رماية مصريات",
    "Category:2000s films": "تصنيف:أفلام إنتاج عقد 2000",
    "Category:World Judo Championships": "تصنيف:بطولة العالم للجودو",
    "Category:Egyptian sport shooters": "تصنيف:لاعبو رماية مصريون",
    "Category:1902 films": "تصنيف:أفلام إنتاج 1902",
    "Category:Military alliances involving Yemen": "تصنيف:تحالفات عسكرية تشمل اليمن",
    "Category:Peruvian television actors": "تصنيف:ممثلو تلفزيون بيروفيون",
    "Category:Fish described in 1995": "تصنيف:أسماك اكتشفت في 1995",
    "Category:Military alliances involving Japan": "تصنيف:تحالفات عسكرية تشمل اليابان",
    "Category:2000s American films": "تصنيف:أفلام أمريكية عقد 2000",
    "Category:Berlin University of the Arts": "تصنيف:جامعة برلين للفنون",
    "Category:Vertebrates described in the 20th century": "تصنيف:فقاريات وصفت في القرن 20",
    "Category:Mammals by century of formal description": "تصنيف:ثدييات حسب قرن الوصف",
    "Category:21st century in film": "تصنيف:القرن 21 في الأفلام",
    "Category:songs about busan": "تصنيف:أغاني عن بوسان",
    "Category:British television chefs": "تصنيف:طباخو تلفاز بريطانيون",
    "Category:Films set in the 21st century": "تصنيف:أفلام تقع أحداثها في القرن 21",
    "Category:Treaties extended to Curaçao": "تصنيف:معاهدات امتدت إلى كوراساو",
    "Category:South Korean television series by production location": "تصنيف:مسلسلات تلفزيونية كورية جنوبية حسب موقع الإنتاج",
    "Category:Mystery films by genre": "تصنيف:أفلام غموض حسب النوع الفني",
    "Category:Israeli people of Northern Ireland descent": "تصنيف:إسرائيليون من أصل أيرلندي شمالي",
    "Category:Sports broadcasters by nationality": "تصنيف:مذيعون رياضيون حسب الجنسية",
    "Category:Spanish sports broadcasters": "تصنيف:مذيعون رياضيون إسبان",
    "Category:Canadian sports businesspeople": "تصنيف:رجال أعمال رياضيون كنديون",
    "Category:Spy films by genre": "تصنيف:أفلام تجسسية حسب النوع الفني",
    "Category:American television series based on British television series": "تصنيف:مسلسلات تلفزيونية أمريكية مبنية على مسلسلات تلفزيونية بريطانية",
    "Category:films by country": "تصنيف:أفلام حسب البلد",
    "Category:Television shows by city of setting": "تصنيف:عروض تلفزيونية حسب مدينة الحدث",
    "Category:Afghan expatriates": "تصنيف:مغتربون أفغان",
    "Category:Ethnic groups of the Dominican Republic": "تصنيف:مجموعات عرقية في جمهورية الدومينيكان",
    "Category:1000s disestablishments in Asia": "تصنيف:انحلالات عقد 1000 في آسيا",
    "Category:Transport companies established in 1909": "تصنيف:شركات نقل أنشئت في 1909",
    "Category:parks in the Roman Empire": "تصنيف:متنزهات في الإمبراطورية الرومانية",
    "Category:Video games about diseases": "تصنيف:ألعاب فيديو عن الأمراض",
    "Category:Television shows set in Australia by city": "تصنيف:عروض تلفزيونية تقع أحداثها في أستراليا حسب المدينة",
    "Category:England amateur international footballers": "تصنيف:لاعبو منتخب إنجلترا لكرة القدم للهواة",
    "Category:War films by genre": "تصنيف:أفلام حربية حسب النوع الفني",
    "Category:Road bridges by country": "تصنيف:جسور طرق حسب البلد",
    "Category:Video games about slavery": "تصنيف:ألعاب فيديو عن العبودية",
    "Category:International women's basketball competitions hosted by Cuba": "تصنيف:منافسات كرة سلة نسائية دولية تستضيفها كوبا",
    "Category:Science fiction films by genre": "تصنيف:أفلام علمية خيالية حسب النوع الفني",
    "Category:Characters in children's literature": "تصنيف:شخصيات في أدب أطفال",
    "Category:Penal system in Afghanistan": "تصنيف:قانون العقوبات في أفغانستان",
    "Category:Afghanistan women's national football team coaches": "تصنيف:مدربو منتخب أفغانستان الوطني لكرة القدم للنساء",
    "Category:Television series by city of location": "تصنيف:مسلسلات تلفزيونية حسب مدينة الموقع",
    "Category:Lists of television characters by series": "تصنيف:قوائم شخصيات تلفزيونية حسب السلسلة",
    "Category:Decades in Oklahoma": "تصنيف:عقود في أوكلاهوما",
    "Category:Fantasy films by genre": "تصنيف:أفلام فانتازيا حسب النوع الفني",
    "Category:Women's national under-18 ice hockey teams": "تصنيف:منتخبات هوكي جليد وطنية نسائية تحت 18 سنة",
    "Category:Women's national ice hockey teams": "تصنيف:منتخبات هوكي جليد وطنية نسائية",
    "Category:1990s disestablishments in Europe": "تصنيف:انحلالات عقد 1990 في أوروبا",
    "Category:1st century BC": "تصنيف:القرن 1 ق م",
    "Category:Comics set in the 1st century BC": "تصنيف:قصص مصورة تقع أحداثها في القرن 1 ق م",
    "Category:Philippine films by subgenre": "تصنيف:أفلام فلبينية حسب النوع الفرعي",
    "Category:2017 American television seasons": "تصنيف:مواسم تلفزيونية أمريكية 2017",
    "Category:Dinosaurs in fiction": "تصنيف:ديناصورات في الخيال",
    "Category:Films shot in China by city": "تصنيف:أفلام مصورة في الصين حسب المدينة",
    "Category:Celtic mythology in popular culture": "تصنيف:أساطير كلتية في الثقافة الشعبية",
    "Category:Fantasy video games": "تصنيف:ألعاب فيديو فانتازيا",
    "Category:2017–18 in Emirati football": "تصنيف:كرة القدم الإماراتية في 2017–18",
    "Category:Rail transport in Sri Lanka by province": "تصنيف:السكك الحديدية في سريلانكا حسب الإقليم",
    "Category:History of the British Army": "تصنيف:تاريخ الجيش البريطاني",
    "Category:History of the Royal Navy": "تصنيف:تاريخ البحرية الملكية",
    "Category:Polish businesspeople": "تصنيف:رجال أعمال بولنديون",
    "Category:Historical fiction by setting": "تصنيف:خيال تاريخي حسب موقع الأحداث",
    "Category:Films by continent": "تصنيف:أفلام حسب القارة",
    "Category:Afghanistan national football team managers": "تصنيف:مدربو منتخب أفغانستان الوطني لكرة القدم",
    "Category:Films by topic": "تصنيف:أفلام حسب الموضوع",
    "Category:ugandan football": "تصنيف:كرة القدم الأوغندية",
    "Category:2017 events": "تصنيف:أحداث 2017",
    "Category:1270s in the Holy Roman Empire": "تصنيف:عقد 1270 في الإمبراطورية الرومانية المقدسة",
    "Category:Belgian athletics coaches": "تصنيف:مدربو ألعاب القوى بلجيكيون",
    "Category:19th-century people by religion": "تصنيف:أشخاص حسب الدين في القرن 19",
    "Category:18th-century people of the Dutch Empire": "تصنيف:أشخاص من الإمبراطورية الهولندية في القرن 18",
    "Category:Films by city of shooting location": "تصنيف:أفلام حسب مدينة التصوير",
    "Category:Films based on television series": "تصنيف:أفلام مبنية على مسلسلات تلفزيونية",
    "Category:History of the Royal Air Force": "تصنيف:تاريخ القوات الجوية الملكية",
    "Category:Ivorian diaspora in Asia": "تصنيف:شتات إيفواري في آسيا",
    "Category:Films by director": "تصنيف:أفلام حسب المخرج",
    "Category:Films by technology": "تصنيف:أفلام حسب التكنولوجيا",
    "Category:Canada men's international soccer players": "تصنيف:لاعبو منتخب كندا لكرة القدم للرجال",
    "Category:American people of the Iraq War": "تصنيف:أمريكيون من حرب العراق",
    "Category:Thriller films by genre": "تصنيف:أفلام إثارة حسب النوع الفني",
    "Category:Action films by genre": "تصنيف:أفلام حركة حسب النوع الفني",
    "Category:Pornographic films by genre": "تصنيف:أفلام إباحية حسب النوع الفني",
    "Category:football in 2050–51": "تصنيف:كرة القدم في 2050–51",
    "Category:10th millennium in fiction": "تصنيف:الألفية 10 في الخيال",
    "Category:2017 sports events": "تصنيف:أحداث رياضية 2017",
    "Category:Cartoonists by publication": "تصنيف:كارتونيون حسب المؤسسة",
    "Category:Video games set in the Byzantine Empire": "تصنيف:ألعاب فيديو تقع أحداثها في الإمبراطورية البيزنطية",
    "Category:Ivorian emigrants": "تصنيف:مهاجرون إيفواريون",
    "Category:2017 events by country": "تصنيف:أحداث 2017 حسب البلد",
    "Category:Women's national sports teams of Cuba": "تصنيف:منتخبات رياضية وطنية نسائية في كوبا",
    "Category:Association football players by women's national team": "تصنيف:لاعبو كرة قدم حسب المنتخب الوطني للنساء",
    "Category:19th-century publications": "تصنيف:منشورات القرن 19",
    "Category:20th-century disestablishments in India": "تصنيف:انحلالات القرن 20 في الهند",
    "Category:Political films by genre": "تصنيف:أفلام سياسة حسب النوع الفني",
    "Category:Penal systems by country": "تصنيف:قانون العقوبات حسب البلد",
    "Category:Ambassadors by mission country": "تصنيف:سفراء حسب بلد البعثة",
    "Category:Mammals described in 2017": "تصنيف:ثدييات اكتشفت في 2017",
    "Category:Films by studio": "تصنيف:أفلام حسب استوديو الإنتاج",
    "Category:Films by movement": "تصنيف:أفلام حسب الحركة",
    "Category:Argentina women's international footballers": "تصنيف:لاعبات منتخب الأرجنتين لكرة القدم للنساء",
    "Category:Attacks on diplomatic missions": "تصنيف:هجمات على بعثات دبلوماسية",
    "Category:Ivorian American": "تصنيف:أمريكيون إيفواريون",
    "Category:1000 disestablishments by country": "تصنيف:انحلالات سنة 1000 حسب البلد",
    "Category:Historical comics": "تصنيف:قصص مصورة تاريخية",
    "Category:multi-sport events at Yemen": "تصنيف:أحداث رياضية متعددة في اليمن",
    "Category:Lists of British television series characters by series": "تصنيف:قوائم شخصيات مسلسلات تلفزيونية بريطانية حسب السلسلة",
    "Category:18th-century Dutch explorers": "تصنيف:مستكشفون هولنديون في القرن 18",
    "Category:1370s conflicts": "تصنيف:نزاعات عقد 1370",
    "Category:2017 American television series": "تصنيف:مسلسلات تلفزيونية أمريكية 2017",
    "Category:History of the British National Party": "تصنيف:تاريخ الحزب الوطني البريطاني",
    "Category:Films by city": "تصنيف:أفلام حسب المدينة",
    "Category:Mystery films by country": "تصنيف:أفلام غموض حسب البلد",
    "Category:LGBT-related films by genre": "تصنيف:أفلام متعلقة بإل جي بي تي حسب النوع الفني",
    "Category:2006 Winter Paralympics events": "تصنيف:أحداث الألعاب البارالمبية الشتوية 2006",
    "Category:July 2018 events by continent": "تصنيف:أحداث يوليو 2018 حسب القارة",
    "Category:Films by setting": "تصنيف:أفلام حسب موقع الأحداث",
    "Category:women in business": "تصنيف:سيدات أعمال",
    "Category:Ambassadors of Afghanistan to Australia": "تصنيف:سفراء أفغانستان إلى أستراليا",
    "Category:British editorial cartoonists": "تصنيف:محررون كارتونيون بريطانيون",
    "Category:1000 disestablishments in Europe": "تصنيف:انحلالات سنة 1000 في أوروبا",
    "Category:Immigrants to the United Kingdom from Aden": "تصنيف:مهاجرون إلى المملكة المتحدة من عدن",
    "Category:Ambassadors of the Ottoman Empire": "تصنيف:سفراء الدولة العثمانية",
    "Category:landmarks in Yemen": "تصنيف:معالم في اليمن",
    "Category:Russian folklore characters": "تصنيف:شخصيات فلكلورية روسية",
    "Category:Comics adapted into films": "تصنيف:قصص مصورة تم تحويلها إلى أفلام",
    "Category:Multi-sport events in the Soviet Union": "تصنيف:أحداث رياضية متعددة في الاتحاد السوفيتي",
    "Category:Australian Internet celebrities": "تصنيف:مشاهير إنترنت أستراليون",
    "Category:Women in business by nationality": "تصنيف:سيدات أعمال حسب الجنسية",
    "Category:Association football players by amateur national team": "تصنيف:لاعبو كرة قدم حسب المنتخب الوطني للهواة",
    "Category:Films by shooting location": "تصنيف:أفلام حسب موقع التصوير",
    "Category:Cape Verde at the Paralympics": "تصنيف:الرأس الأخضر في الألعاب البارالمبية",
    "Category:Afghan emigrants": "تصنيف:مهاجرون أفغان",
    "Category:People of Ivorian descent": "تصنيف:أشخاص من أصل إيفواري",
    "Category:People by nationality and status": "تصنيف:أشخاص حسب الجنسية والحالة",
    "Category:Australia international soccer players": "تصنيف:لاعبو منتخب أستراليا لكرة القدم",
    "Category:Dinosaurs in video games": "تصنيف:ألعاب فيديو ديناصورات",
    "Category:1980 sports events in Europe": "تصنيف:أحداث 1980 الرياضية في أوروبا",
    "Category:IndyCar": "تصنيف:أندي كار",
    "Category:Historical webcomics": "تصنيف:ويب كومكس تاريخية",
    "Category:Paralympic competitors for Cape Verde": "تصنيف:منافسون بارالمبيون من الرأس الأخضر",
    "Category:Films set in national parks": "تصنيف:أفلام تقع أحداثها في متنزهات وطنية",
    "Category:Health in North Dakota": "تصنيف:الصحة في داكوتا الشمالية",
    "Category:Award winners by nationality": "تصنيف:حائزو جوائز حسب الجنسية",
    "Category:Horror films by genre": "تصنيف:أفلام رعب حسب النوع الفني",
    "Category:Sports films by genre": "تصنيف:أفلام رياضية حسب النوع الفني",
    "Category:Films by producer": "تصنيف:أفلام حسب المنتج",
    "Category:Historical poems": "تصنيف:قصائد تاريخية",
    "Category:Airlines established in 1968": "تصنيف:شركات طيران أنشئت في 1968",
    "Category:Films by genre": "تصنيف:أفلام حسب النوع الفني",
    "Category:Immigration to New Zealand": "تصنيف:الهجرة إلى نيوزيلندا",
    "Category:13th century establishments in the Roman Empire": "تصنيف:تأسيسات القرن 13 في الإمبراطورية الرومانية",
    "Category:Ambassadors to the Ottoman Empire": "تصنيف:سفراء لدى الدولة العثمانية",
    "Category:Polish women in business": "تصنيف:سيدات أعمال بولنديات",
    "Category:440s": "تصنيف:عقد 440",
    "Category:Association football players by under-21 national team": "تصنيف:لاعبو كرة قدم حسب المنتخب الوطني تحت 21 سنة",
    "Category:1990s BC disestablishments in Asia": "تصنيف:انحلالات عقد 1990 ق م في آسيا",
    "Category:Musical films by genre": "تصنيف:أفلام موسيقية حسب النوع الفني",
    "Category:Olympic gold medalists for the United States in alpine skiing": "تصنيف:فائزون بميداليات ذهبية أولمبية من الولايات المتحدة في التزلج على المنحدرات الثلجية",
    "Category:Association football": "تصنيف:كرة القدم",
    "Category:Olympic medalists in alpine skiing": "تصنيف:فائزون بميداليات أولمبية في التزلج على المنحدرات الثلجية",
    "Category:20th-century railway accidents": "تصنيف:حوادث سكك حديدية القرن 20",
    "Category:Emirati football in 2017": "تصنيف:كرة القدم الإماراتية في 2017",
    "Category:Airlines by year of establishment": "تصنيف:شركات طيران حسب سنة التأسيس",
    "Category:Television stations by country": "تصنيف:محطات تلفزيونية حسب البلد",
    "Category:November 2006 in Yemen": "تصنيف:نوفمبر 2006 في اليمن",
    "Category:Expatriate association football managers by country of residence": "تصنيف:مدربو كرة قدم مغتربون حسب بلد الإقامة",
    "Category:Films based on comics": "تصنيف:أفلام مبنية على قصص مصورة",
    "Category:Destroyed churches by country": "تصنيف:كنائس مدمرة حسب البلد",
    "Category:19th-century actors by religion": "تصنيف:ممثلون حسب الدين في القرن 19",
    "Category:19th-century actors": "تصنيف:ممثلون في القرن 19",
    "Category:April 1983 sports events": "تصنيف:أحداث رياضية أبريل 1983",
    "Category:Expatriate women's footballers by location": "تصنيف:لاعبات كرة قدم مغتربات حسب الموقع",
    "Category:American cinema by decade": "تصنيف:السينما الأمريكية حسب العقد",
    "Category:Sports coaches by nationality": "تصنيف:مدربون رياضيون حسب الجنسية",
    "Category:Films by type": "تصنيف:أفلام حسب الفئة",
    "Category:People by former country": "تصنيف:أشخاص حسب البلد السابق",
    "Category:Video games based on Egyptian mythology": "تصنيف:ألعاب فيديو مبنية على أساطير مصرية",
    "Category:Afghan criminal law": "تصنيف:القانون الجنائي الأفغاني",
    "Category:Video games based on mythology": "تصنيف:ألعاب فيديو مبنية على أساطير",
    "Category:Historical short stories": "تصنيف:قصص قصيرة تاريخية",
    "Category:National under-18 ice hockey teams": "تصنيف:منتخبات هوكي جليد وطنية تحت 18 سنة",
    "Category:Women's organizations based in Cuba": "تصنيف:منظمات نسائية مقرها في كوبا",
    "Category:Association football players by under-23 national team": "تصنيف:لاعبو كرة قدم حسب المنتخب الوطني تحت 23 سنة",
    "Category:Publications by year of establishment": "تصنيف:منشورات حسب سنة التأسيس",
    "Category:Women's national youth association football teams": "تصنيف:منتخبات كرة قدم وطنية للشابات",
    "Category:Argentina at the Winter Olympics": "تصنيف:الأرجنتين في الألعاب الأولمبية الشتوية",
    "Category:Films by language": "تصنيف:أفلام حسب اللغة",
    "Category:21st-century in Qatar": "تصنيف:القرن 21 في قطر",
    "Category:2015 American television": "تصنيف:2015 التلفزة الأمريكية",
    "Category:Lists of action television characters by series": "تصنيف:قوائم شخصيات تلفزيونية حركة حسب السلسلة",
    "Category:00s establishments in the Roman Empire": "تصنيف:تأسيسات عقد 00 في الإمبراطورية الرومانية",
    "Category:977 by country": "تصنيف:977 حسب البلد",
    "Category:Swaziland at multi-sport events": "تصنيف:سوازيلاند في الأحداث الرياضية المتعددة",
    "Category:Publications by format": "تصنيف:منشورات حسب التنسيق",
    "Category:Association football players by youth national team": "تصنيف:لاعبو كرة قدم حسب المنتخب الوطني للشباب",
    "Category:Soviet Union at multi-sport events": "تصنيف:الاتحاد السوفيتي في الأحداث الرياضية المتعددة",
    "Category:21st century in the Czech Republic": "تصنيف:القرن 21 في التشيك",
    "Category:Television characters by series": "تصنيف:شخصيات تلفزيونية حسب السلسلة",
    "Category:Holocaust literature": "تصنيف:أدب هولوكوست",
    "Category:14th-century establishments in India": "تصنيف:تأسيسات القرن 14 في الهند",
    "Category:People executed by Afghanistan": "تصنيف:أشخاص أعدموا من قبل أفغانستان",
    "Category:Lists of association football players by national team": "تصنيف:قوائم لاعبو كرة قدم حسب المنتخب الوطني",
    "Category:Olympic medalists for the United States": "تصنيف:فائزون بميداليات أولمبية من الولايات المتحدة",
    "Category:Dark fantasy video games": "تصنيف:ألعاب فيديو فانتازيا مظلمة",
    "Category:2006 establishments by country": "تصنيف:تأسيسات سنة 2006 حسب البلد",
    "Category:Olympic gold medalists for the United States": "تصنيف:فائزون بميداليات ذهبية أولمبية من الولايات المتحدة",
    "Category:Female comics writers": "تصنيف:كاتبات قصص مصورة",
    "Category:Editorial cartoonists from Northern Ireland": "تصنيف:محررون كارتونيون من أيرلندا الشمالية",
    "Category:Emirati football in 2017–18": "تصنيف:كرة القدم الإماراتية في 2017–18",
    "Category:European women in business": "تصنيف:سيدات أعمال أوروبيات",
    "Category:Drama films by country": "تصنيف:أفلام درامية حسب البلد",
    "Category:Scottish traditions": "تصنيف:تراث إسكتلندي",
    "Category:Comics based on films": "تصنيف:قصص مصورة مبنية على أفلام",
    "Category:Airlines of Afghanistan": "تصنيف:شركات طيران أفغانستان",
    "Category:Video games set in prehistory": "تصنيف:ألعاب فيديو تقع أحداثها في ما قبل التاريخ",
    "Category:Ambassadors of Afghanistan to Argentina": "تصنيف:سفراء أفغانستان إلى الأرجنتين",
    "Category:African women's national association football teams": "تصنيف:منتخبات كرة قدم وطنية نسائية إفريقية",
    "Category:Expatriate women's association football players": "تصنيف:لاعبات كرة قدم مغتربات",
    "Category:Cargo airlines of the Philippines": "تصنيف:شركات الشحن الجوي في الفلبين",
    "Category:Films by culture": "تصنيف:أفلام حسب الثقافة",
    "Category:Television series by country of shooting location": "تصنيف:مسلسلات تلفزيونية حسب بلد التصوير",
    "Category:Films by date": "تصنيف:أفلام حسب التاريخ",
    "Category:Polish women by occupation": "تصنيف:بولنديات حسب المهنة",
    "Category:Equatorial Guinea women's national football team": "تصنيف:منتخب غينيا الاستوائية الوطني لكرة القدم للنساء",
    "Category:Television shows filmed in Algeria": "تصنيف:عروض تلفزيونية صورت في الجزائر",
    "Category:Drama television characters by series": "تصنيف:شخصيات تلفزيونية درامية حسب السلسلة",
    "Category:Drama films by genre": "تصنيف:أفلام درامية حسب النوع الفني",
    "Category:Romance films by genre": "تصنيف:أفلام رومانسية حسب النوع الفني",
    "Category:Television series produced in Seoul": "تصنيف:مسلسلات تلفزيونية أنتجت في سول",
    "Category:Rail transport in the United Kingdom": "تصنيف:السكك الحديدية في المملكة المتحدة",
    "Category:Teen films by genre": "تصنيف:أفلام مراهقة حسب النوع الفني",
    "Category:2017 in Emirati football": "تصنيف:كرة القدم الإماراتية في 2017",
    "Category:Awards by country": "تصنيف:جوائز حسب البلد",
    "Category:Nauru international soccer players": "تصنيف:لاعبو منتخب ناورو لكرة القدم",
    "Category:Ivorian diaspora by country": "تصنيف:شتات إيفواري حسب البلد",
    "Category:Ambassadors by country of origin": "تصنيف:سفراء حسب البلد الأصل",
    "Category:Works adapted for other media": "تصنيف:أعمال تم تحويلها إلى وسائط أخرى",
    "Category:Fantasy television characters by series": "تصنيف:شخصيات تلفزيونية فانتازيا حسب السلسلة",
    "Category:European national under-21 association football teams": "تصنيف:منتخبات كرة قدم وطنية أوروبية تحت 21 سنة",
    "Category:Comedy films by genre": "تصنيف:أفلام كوميدية حسب النوع الفني",
    "Category:Prisoners and detainees of Afghanistan": "تصنيف:سجناء ومعتقلون في أفغانستان",
    "Category:Prisons in Afghanistan": "تصنيف:سجون في أفغانستان",
    "Category:Nuclear power by country": "تصنيف:طاقة نووية حسب البلد",
    "Category:French comic": "تصنيف:قصص مصورة فرنسية",
    "Category:Immigrants to New Zealand": "تصنيف:مهاجرون إلى نيوزيلندا",
    "Category:Cape Verdean football managers": "تصنيف:مدربو كرة قدم أخضريون",
    "Category:Films based on American comics": "تصنيف:أفلام مبنية على قصص مصورة أمريكية",
    "Category:April 1983 events in Europe": "تصنيف:أحداث أبريل 1983 في أوروبا",
    "Category:Crime films by genre": "تصنيف:أفلام جريمة حسب النوع الفني",
    "Category:American television episodes": "تصنيف:حلقات تلفزيونية أمريكية",
    "Category:20th-century Albanian sports coaches": "تصنيف:مدربون رياضيون ألبان في القرن 20",
    "Category:Films by audience": "تصنيف:أفلام حسب الجمهور",
    "Category:Afghan diplomats": "تصنيف:دبلوماسيون أفغان",
    "Category:Internees at the Sheberghan Prison": "تصنيف:معتقلين في سجن شيبرغان",
    "Category:2017 American television episodes": "تصنيف:حلقات تلفزيونية أمريكية 2017",
    "Category:Ivorian expatriates": "تصنيف:مغتربون إيفواريون",
    "Category:Films by source": "تصنيف:أفلام حسب المصدر",
    "Category:Films by country": "تصنيف:أفلام حسب البلد",
    "Category:Historical television series": "تصنيف:مسلسلات تلفزيونية تاريخية",
    "Category:Women's sports teams in Cuba": "تصنيف:فرق رياضية نسائية في كوبا",
    "Category:Television programs by geographic setting": "تصنيف:برامج تلفزيونية حسب الموقع الجغرافي للأحداث",
    "Category:Erotic films by genre": "تصنيف:أفلام إغرائية حسب النوع الفني",
    "Category:South Africa international soccer players": "تصنيف:لاعبو منتخب جنوب إفريقيا لكرة القدم",
    "Category:Ambassadors of Afghanistan": "تصنيف:سفراء أفغانستان",
    "Category:2000s in the United States by state": "تصنيف:عقد 2000 في الولايات المتحدة حسب الولاية",
    "Category:Manufacturing companies established in the 2nd millennium": "تصنيف:شركات تصنيع أنشئت في الألفية 2",
    "Category:Historical novels": "تصنيف:روايات تاريخية",
    "Category:Handball competitions by country": "تصنيف:منافسات كرة يد حسب البلد",
    "Category:History of British Rail": "تصنيف:تاريخ السكك الحديدية البريطانية",
    "Category:Television series endings by year": "تصنيف:مسلسلات تلفزيونية حسب سنة انتهاء العرض",
    "Category:440s bc": "تصنيف:عقد 440 ق م",
    "Category:Association football players by under-20 national team": "تصنيف:لاعبو كرة قدم حسب المنتخب الوطني تحت 20 سنة",
    "Category:Publications disestablished in 1946": "تصنيف:منشورات انحلت في 1946",
    "Category:Decades by country": "تصنيف:عقود حسب البلد",
    "Category:Documentary films by genre": "تصنيف:أفلام وثائقية حسب النوع الفني",
    "Category:Television series produced in Alberta": "تصنيف:مسلسلات تلفزيونية أنتجت في ألبرتا",
    "Category:Categories by province of Saudi Arabia": "تصنيف:تصنيفات حسب المقاطعة في المملكة العربية السعودية",
    "Category:Skiing coaches": "تصنيف:مدربو تزلج",
    "Category:French comic strips": "تصنيف:شرائط مصورة فرنسية",
    "Category:Olympic competitors for Cape Verde": "تصنيف:منافسون أولمبيون من الرأس الأخضر",
    "Category:Publications by year of disestablishment": "تصنيف:منشورات حسب سنة الانحلال",
    "Category:American award winners": "تصنيف:أمريكيون حائزو جوائز",
    "Category:Equatoguinean women's footballers": "تصنيف:لاعبات كرة قدم غينيات استوائيات",
    "Category:Airlines by dependent territory": "تصنيف:شركات طيران حسب الأقاليم التابعة",
    "Category:British Rail": "تصنيف:السكك الحديدية البريطانية",
    "Category:Scottish popular culture": "تصنيف:ثقافة شعبية إسكتلندية",
    "Category:Cuba women's national basketball team": "تصنيف:منتخب كوبا الوطني لكرة السلة للنساء",
    "Category:American people by status": "تصنيف:أمريكيون حسب الحالة",
    "Category:2017 American television series debuts": "تصنيف:مسلسلات تلفزيونية أمريكية بدأ عرضها في 2017",
    "Category:Adventure films by genre": "تصنيف:أفلام مغامرات حسب النوع الفني",
    "Category:2017 American television series endings": "تصنيف:مسلسلات تلفزيونية أمريكية انتهت في 2017",
    "Category:Expatriate male actors in New Zealand": "تصنيف:ممثلون ذكور مغتربون في نيوزيلندا",
    "Category:Coaches of national cricket teams": "تصنيف:مدربو منتخبات كريكت وطنية",
    "Category:Expatriate male actors": "تصنيف:ممثلون ذكور مغتربون",
    "Category:Coaches of the West Indies national cricket team": "تصنيف:مدربو منتخب الهند الغربية الوطني للكريكت",
    "Category:Coaches of Yemen national cricket team": "تصنيف:مدربو منتخب اليمن الوطني للكريكت",
    "Category:Swedish oncologists": "تصنيف:أطباء أورام سويديون",
    "Category:Egyptian oncologists": "تصنيف:أطباء أورام مصريون",
    "Category:Vehicle manufacturing companies disestablished in 1904": "تصنيف:شركات تصنيع مركبات انحلت في 1904",
    "Category:2004 residency shows": "",
    "Category:American track and field coaches": "",
    "Category:Association football players by B national team": "",
    "Category:Comics publications": "",
    "Category:Economy of Oceania by country": "",
    "Category:Films based on works by comic book writers": "",
    "Category:Geography of Africa by country": "",
    "Category:History of association football clubs in the United Kingdom": "",
    "Category:History of companies of the United Kingdom": "",
    "Category:History of organisations based in England": "",
    "Category:History of organisations based in Northern Ireland": "",
    "Category:History of organisations based in Scotland": "",
    "Category:History of organisations based in Wales": "",
    "Category:History of organisations based in the United Kingdom": "",
    "Category:History of rail transport in the United Kingdom": "",
    "Category:Holding companies established in 1942": "",
    "Category:Ireland international rules football team coaches": "",
    "Category:January 2017 events by continent": "",
    "Category:January 2017 events": "",
    "Category:January 2017 sports events by country": "",
    "Category:January 2017 sports events": "",
    "Category:Martial arts films by genre": "",
    "Category:National association football team managers": "",
    "Category:Recipients of Afghan presidential pardons": "",
    "Category:Residency shows by artist": "",
    "Category:Residency shows in the Las Vegas Valley": "",
    "Category:Ugandan": "",
    "Category:United States Virgin Islands international soccer players": "",
    "Category:United States men's international soccer players": "",
    "Category:Western (genre) films by genre": "",
}
# ---
Yell = {
    "Category:10th-century BC architecture": "تصنيف:عمارة القرن 10 ق م",
    "Category:1st-century architecture": "تصنيف:عمارة القرن 1",
    "Category:1st-millennium architecture": "تصنيف:عمارة الألفية 1",
    "Category:1st-millennium literature": "تصنيف:أدب الألفية 1",
    "Category:American basketball coaches by state": "تصنيف:مدربو كرة سلة أمريكيون حسب الولاية",
    "Category:American nuclear medicine physicians": "تصنيف:أطباء طب نووي أمريكيون",
    "Category:Archaeology of Europe by period": "تصنيف:علم الآثار في أوروبا حسب الحقبة",
    "Category:Australian male sprinters": "تصنيف:عداؤون سريعون ذكور أستراليون",
    "Category:Basketball coaches from Indiana": "تصنيف:مدربو كرة سلة من إنديانا",
    "Category:Basketball people from Indiana": "تصنيف:أعلام كرة سلة من إنديانا",
    "Category:Basketball players from Indiana": "تصنيف:لاعبو كرة سلة من إنديانا",
    "Category:Books about politics by country": "تصنيف:كتب عن سياسة حسب البلد",
    "Category:Bridges in Wales by type": "تصنيف:جسور في ويلز حسب الفئة",
    "Category:Canadian nuclear medicine physicians": "تصنيف:أطباء طب نووي كنديون",
    "Category:Croatian nuclear medicine physicians": "تصنيف:أطباء طب نووي كروات",
    "Category:Egyptian oncologists": "تصنيف:أطباء أورام مصريون",
    "Category:Financial services companies disestablished in 1905": "",
    "Category:German nuclear medicine physicians": "تصنيف:أطباء طب نووي ألمان",
    "Category:Hong Kong national football team matches": "",
    "Category:Icelandic male athletes": "تصنيف:لاعبو قوى ذكور آيسلنديون",
    "Category:Icelandic male runners": "تصنيف:عداؤون ذكور آيسلنديون",
    "Category:Icelandic male steeplechase runners": "تصنيف:عداؤو موانع ذكور آيسلنديون",
    "Category:Iranian nuclear medicine physicians": "تصنيف:أطباء طب نووي إيرانيون",
    "Category:Irish association football managers": "تصنيف:مدربو كرة قدم أيرلنديون",
    "Category:Male long-distance runners": "تصنيف:عداؤو مسافات طويلة ذكور",
    "Category:Male runners by nationality": "تصنيف:عداؤون ذكور حسب الجنسية",
    "Category:Male steeplechase runners": "تصنيف:عداؤو موانع ذكور",
    "Category:Medical doctors by specialty and nationality": "تصنيف:أطباء حسب التخصص والجنسية",
    "Category:Moroccan male middle-distance runners": "تصنيف:عداؤو مسافات متوسطة ذكور مغاربة",
    "Category:National youth sports teams by country": "تصنيف:منتخبات رياضية وطنية شبابية حسب البلد",
    "Category:Pakistani psychiatrists": "تصنيف:أطباء نفسيون باكستانيون",
    "Category:Portuguese healthcare managers": "تصنيف:مدراء رعاية صحية برتغاليون",
    "Category:Prehistory of Venezuela": "تصنيف:فنزويلا ما قبل التاريخ",
    "Category:Publishing companies disestablished in 1905": "",
    "Category:Republic of Ireland football managers": "تصنيف:مدربو كرة قدم أيرلنديون",
    "Category:Research institutes established in 1900": "تصنيف:معاهد أبحاث أسست في 1900",
    "Category:Scholars by subfield": "تصنيف:دارسون حسب الحقل الفرعي",
    "Category:Subfields by academic discipline": "تصنيف:حقول فرعية حسب التخصص الأكاديمي",
    "Category:Swedish oncologists": "تصنيف:أطباء أورام سويديون",
    "Category:Transport disasters in 2017": "تصنيف:كوارث نقل في 2017",
    "Category:Vehicle manufacturing companies disestablished in 1904": "تصنيف:شركات تصنيع المركبات انحلت في 1904",
    "Category:design companies disestablished in 1905": "تصنيف:شركات تصميم انحلت في 1905",
    "category:books about politics by country": "تصنيف:كتب عن سياسة حسب البلد"
}

indianalist = {
    "Category:1950s criminal comedy films": "تصنيف:أفلام كوميديا الجريمة عقد 1950",
    "Category:1960s black comedy films": "تصنيف:أفلام كوميدية سوداء عقد 1960",
    "Category:1960s criminal comedy films": "تصنيف:أفلام كوميديا الجريمة عقد 1960",
    "Category:1960s sex comedy films": "",
    "Category:1970s black comedy films": "تصنيف:أفلام كوميدية سوداء عقد 1970",
    "Category:1970s criminal comedy films": "تصنيف:أفلام كوميديا الجريمة عقد 1970",
    "Category:1970s sex comedy films": "",
    "Category:1980s black comedy films": "تصنيف:أفلام كوميدية سوداء عقد 1980",
    "Category:1980s criminal comedy films": "تصنيف:أفلام كوميديا الجريمة عقد 1980",
    "Category:American basketball players by ethnic or national origin": "تصنيف:لاعبو كرة سلة أمريكيون حسب الأصل العرقي أو الوطني",
    "Category:Baseball players from Massachusetts": "تصنيف:لاعبو كرة قاعدة من ماساتشوستس",
    "Category:Basketball players from Massachusetts": "تصنيف:لاعبو كرة سلة من ماساتشوستس",
    "Category:Boxers from Massachusetts": "تصنيف:ملاكمون من ماساتشوستس",
    "Category:Golfers from Massachusetts": "تصنيف:لاعبو غولف من ماساتشوستس",
    "Category:Ice hockey people from Massachusetts": "تصنيف:أعلام هوكي جليد من ماساتشوستس",
    "Category:Kickboxers from Massachusetts": "تصنيف:مقاتلو كيك بوكسنغ من ماساتشوستس",
    "Category:Lacrosse players from Massachusetts": "تصنيف:لاعبو لاكروس من ماساتشوستس",
    "Category:Mixed martial artists from Massachusetts": "تصنيف:مقاتلو فنون قتالية مختلطة من ماساتشوستس",
    "Category:Players of American football from Massachusetts": "تصنيف:لاعبو كرة قدم أمريكية من ماساتشوستس",
    "Category:Professional wrestlers from Massachusetts": "تصنيف:مصارعون محترفون من ماساتشوستس",
    "Category:Racing drivers from Massachusetts": "تصنيف:سائقو سيارات سباق من ماساتشوستس",
    "Category:Soccer players from Massachusetts": "تصنيف:لاعبو كرة قدم من ماساتشوستس",
    "Category:Sports coaches from Massachusetts": "تصنيف:مدربو رياضة من ماساتشوستس",
    "Category:Sportspeople from Boston": "تصنيف:رياضيون من بوسطن",
    "Category:Sportswriters from Massachusetts": "تصنيف:كتاب رياضيون من ماساتشوستس",
    "Category:Swimmers from Massachusetts": "تصنيف:سباحون من ماساتشوستس",
    "Category:Tennis people from Massachusetts": "تصنيف:أعلام كرة مضرب من ماساتشوستس",
    "Category:Track and field athletes from Massachusetts": "تصنيف:رياضيو المسار والميدان من ماساتشوستس"
}
# ---
c21st_list = {
    "Category:1902 films": "تصنيف:أفلام إنتاج 1902",
    "Category:1994–95 in European rugby union by country": "تصنيف:اتحاد الرجبي الأوروبي في 1994–95 حسب البلد",
    "Category:2000s American films": "تصنيف:أفلام أمريكية في عقد 2000",
    "Category:2000s films": "تصنيف:أفلام إنتاج عقد 2000",
    "Category:2000s in American cinema": "تصنيف:السينما الأمريكية في عقد 2000",
    "Category:2000s in film": "تصنيف:عقد 2000 في الأفلام",
    "Category:21st century in film": "تصنيف:القرن 21 في الأفلام",
    "Category:21st-century films": "تصنيف:أفلام القرن 21",
    "Category:Animals by period of description": "",
    "Category:Animals by year of formal description": "تصنيف:حيوانات حسب سنة الوصف",
    "Category:Berlin University of the Arts": "تصنيف:جامعة برلين للفنون",
    "Category:Books about automobiles": "تصنيف:كتب عن سيارات",
    "Category:British television chefs": "تصنيف:طباخو تلفاز بريطانيون",
    "Category:Disney animated films": "تصنيف:أفلام رسوم متحركة ديزني",
    "Category:Dutch Africanists": "",
    "Category:Egyptian female sport shooters": "تصنيف:لاعبات رماية مصريات",
    "Category:Egyptian male sport shooters": "تصنيف:لاعبو رماية ذكور مصريون",
    "Category:Egyptian sport shooters": "تصنيف:لاعبو رماية مصريون",
    "Category:Experimental film festivals": "",
    "Category:Films about automobiles": "تصنيف:أفلام عن سيارات",
    "Category:Films set in the 21st century": "تصنيف:أفلام تقع أحداثها في القرن 21",
    "Category:Fish described in 1995": "تصنيف:أسماك وصفت في 1995",
    "Category:Mammals by century of formal description": "تصنيف:ثدييات حسب قرن الوصف",
    "Category:Military alliances involving Japan": "تصنيف:تحالفات عسكرية تشمل اليابان",
    "Category:Military alliances involving Yemen": "تصنيف:تحالفات عسكرية تشمل اليمن",
    "Category:Military organization by country": "تصنيف:منظمات عسكرية حسب البلد",
    "Category:Olympic shooters of Egypt": "تصنيف:رماة أولمبيون من مصر",
    "Category:Organists of Ely Cathedral": "",
    "Category:Participants in British reality television series": "تصنيف:مشاركون في مسلسلات تلفزيونية واقعية بريطانية",
    "Category:Peruvian documentary film directors": "",
    "Category:Peruvian television actors": "تصنيف:ممثلو تلفزيون بيرويون",
    "Category:Songs about automobiles": "تصنيف:أغاني عن سيارات",
    "Category:Tetrapods by century of formal description": "تصنيف:رباعيات الأطراف حسب قرن الوصف",
    "Category:Treaties extended to Curaçao": "تصنيف:اتفاقيات امتدت إلى كوراساو",
    "Category:Vertebrates described in the 20th century": "تصنيف:فقاريات وصفت في القرن 20",
    "Category:Women's universities and colleges in India": "تصنيف:جامعات نسائية وكليات في الهند",
    "Category:Works about automobiles": "تصنيف:أعمال عن سيارات",
    "Category:Works about taxicabs": "",
    "Category:World Judo Championships": "تصنيف:بطولة العالم للجودو",
    "Category:documentary filmmakers by nationality": "",
    "Category:songs about busan": "تصنيف:أغاني عن بوسان",
    "Category:yemeni war filmmakers": ""
}

# ---
shar_list ={
    "Category:American Cinema Editors": "تصنيف:محررون سينمائون أمريكيون",
    "Category:Argentine multi-instrumentalists": "تصنيف:عازفون على عدة آلات أرجنتينيون",
    "Category:Argentine songwriters": "تصنيف:كتاب أغان أرجنتينيون",
    "Category:Crime in Pennsylvania": "تصنيف:جريمة في بنسلفانيا",
    "Category:Crimes in Pennsylvania": "تصنيف:جرائم في بنسلفانيا",
    "Category:EMI Latin artists": "",
    "Category:Films set in China by city": "تصنيف:أفلام تقع أحداثها في الصين حسب المدينة",
    "Category:Illustrious Citizens of Buenos Aires": "",
    "Category:Latin Grammy Lifetime Achievement Award winners": "",
    "Category:Military science fiction films": "",
    "Category:Multi-instrumentalists": "تصنيف:عازفون على عدة آلات",
    "Category:Multi-sport clubs by country": "تصنيف:أندية متعددة الرياضات حسب البلد",
    "Category:People from Buenos Aires": "تصنيف:أشخاص من بوينس آيرس",
    "Category:Rock en Español musicians": "",
    "Category:Seasons in Omani football": "تصنيف:مواسم في كرة القدم العمانية",
    "Category:Singers from Buenos Aires": "تصنيف:مغنون من بوينس آيرس",
    "Category:Sports organisations of Andorra": "تصنيف:منظمات رياضية في أندورا",
    "Category:Women's sports organizations in the United States": "تصنيف:منظمات الرياضات النسوية في الولايات المتحدة"
}

# ---
impooor_list = {
    "Category:2006 in Northern Ireland sport": "تصنيف:رياضة أيرلندية شمالية في 2006",
    "Category:2006 in north korean sport": "تصنيف:رياضة كورية شمالية في 2006",
    "Category:2018 Summer Youth Olympics events": "تصنيف:أحداث الألعاب الأولمبية الشبابية الصيفية 2018",
    "Category:Afghan competitors by sports event": "تصنيف:منافسون أفغان حسب الحدث الرياضي",
    "Category:Argentina at the Universiade": "تصنيف:الأرجنتين في الألعاب الجامعية",
    "Category:Athletics at the Summer Universiade navigational boxes": "تصنيف:صناديق تصفح ألعاب القوى في الألعاب الجامعية الصيفية",
    "Category:Athletics at the Universiade navigational boxes": "تصنيف:صناديق تصفح ألعاب القوى في الألعاب الجامعية",
    "Category:Australia at the Summer Universiade": "تصنيف:أستراليا في الألعاب الجامعية الصيفية",
    "Category:Canadian sports businesspeople": "تصنيف:شخصيات أعمال رياضيون كنديون",
    "Category:Cross-country skiers at the 1992 Winter Paralympics": "تصنيف:متزحلقون ريفيون في الألعاب البارالمبية الشتوية 1992",
    "Category:Female short track speed skaters": "تصنيف:متزلجات على مسار قصير",
    "Category:Female single skaters from Georgia (country)": "تصنيف:متزلجات فرديات من جورجيا",
    "Category:Female speed skaters": "تصنيف:متزلجات سرعة",
    "Category:Figure skaters at the 2002 Winter Olympics": "تصنيف:متزلجون فنيون في الألعاب الأولمبية الشتوية 2002",
    "Category:Figure skaters at the 2003 Asian Winter Games": "تصنيف:متزلجون فنيون في الألعاب الآسيوية الشتوية 2003",
    "Category:Figure skaters at the 2007 Winter Universiade": "تصنيف:متزلجون فنيون في الألعاب الجامعية الشتوية 2007",
    "Category:Figure skaters by competition": "تصنيف:متزلجون فنيون حسب المنافسة",
    "Category:Figure skating coaches": "تصنيف:مدربو تزلج فني",
    "Category:Figure skating films": "تصنيف:أفلام تزلج فني",
    "Category:Figure skating media": "تصنيف:إعلام تزلج فني",
    "Category:Figure skating on television": "تصنيف:التزلج الفني على التلفاز",
    "Category:Figure skating people": "تصنيف:أعلام تزلج فني",
    "Category:Figure skating reality television participants": "",
    "Category:Figure skating reality television series": "",
    "Category:Films about Olympic boxing": "تصنيف:أفلام عن بوكسينغ أولمبي",
    "Category:Films about Olympic equestrian sports": "",
    "Category:Films about Olympic figure skating": "تصنيف:أفلام عن تزلج فني أولمبي",
    "Category:Films about Olympic gymnastics": "تصنيف:أفلام عن جمباز أولمبي",
    "Category:Films about Olympic skiing": "تصنيف:أفلام عن تزلج أولمبي",
    "Category:Films about Olympic swimming and diving": "تصنيف:أفلام عن سباحة أولمبية والغطس",
    "Category:Films about Olympic track and field": "تصنيف:أفلام عن سباقات مضمار وميدان أولمبي",
    "Category:Films about the Olympic Games by athletic event": "تصنيف:أفلام عن الألعاب الأولمبية حسب حدث ألعاب القوى",
    "Category:Government of Saint Barthélemy": "تصنيف:حكومة سان بارتيلمي",
    "Category:Gymnastics organizations": "تصنيف:منظمات جمباز",
    "Category:International sports competitions hosted by Mexico": "تصنيف:منافسات رياضية دولية استضافتها المكسيك",
    "Category:Italian defectors to the Soviet Union": "تصنيف:إيطاليون منشقون إلى الاتحاد السوفيتي",
    "Category:Languages of the Cayman Islands": "تصنيف:لغات جزر كايمان",
    "Category:Moroccan competitors by sports event": "تصنيف:منافسون مغاربة حسب الحدث الرياضي",
    "Category:Nations at the 2010 Summer Youth Olympics": "تصنيف:بلدان في الألعاب الأولمبية الشبابية الصيفية 2010",
    "Category:Norwegian figure skaters": "تصنيف:متزلجون فنيون نرويجيون",
    "Category:Norwegian male pair skaters": "تصنيف:متزلجون فنيون على الجليد ذكور نرويجيون",
    "Category:Norwegian male single skaters": "تصنيف:متزلجون فرديون ذكور نرويجيون",
    "Category:Norwegian pair skaters": "تصنيف:متزلجون فنيون على الجليد نرويجيون",
    "Category:Norwegian short track speed skaters": "تصنيف:متزلجون على مسار قصير نرويجيون",
    "Category:Olympic figure skaters by country": "تصنيف:متزلجون فنيون أولمبيون حسب البلد",
    "Category:Olympic figure skaters by year": "تصنيف:متزلجون فنيون أولمبيون حسب السنة",
    "Category:Olympic figure skaters of Argentina": "تصنيف:متزلجون فنيون أولمبيون من الأرجنتين",
    "Category:Olympic figure skaters of Armenia": "تصنيف:متزلجون فنيون أولمبيون من أرمينيا",
    "Category:Olympic figure skaters of Australia": "تصنيف:متزلجون فنيون أولمبيون من أستراليا",
    "Category:Olympic figure skating": "تصنيف:تزلج فني أولمبي",
    "Category:Olympic short track speed skaters of Japan": "تصنيف:متزلجون على مسار قصير أولمبيون من اليابان",
    "Category:People in arts occupations by nationality": "تصنيف:مهن أشخاص في الفنون حسب الجنسية",
    "Category:Roller skaters at the 2003 Pan American Games": "تصنيف:متزلجون بالعجلات في دورة الألعاب الأمريكية 2003",
    "Category:Ski jumpers at the 2007 Winter Universiade": "تصنيف:متزلجو قفز في الألعاب الجامعية الشتوية 2007",
    "Category:Ski jumping at the Winter Universiade": "تصنيف:القفز التزلجي في الألعاب الجامعية الشتوية",
    "Category:Spanish sports broadcasters": "تصنيف:مذيعو رياضية إسبانية",
    "Category:Sports at the Summer Universiade": "تصنيف:ألعاب رياضية في الألعاب الجامعية الصيفية",
    "Category:Sports broadcasters by nationality": "تصنيف:مذيعو رياضية حسب الجنسية",
    "Category:Sports competitors by nationality and competition": "تصنيف:منافسون رياضيون حسب الجنسية والمنافسة",
    "Category:Sports organisations by decade of establishment": "تصنيف:منظمات رياضية حسب عقد التأسيس",
    "Category:Table tennis clubs": "تصنيف:أندية كرة طاولة",
    "Category:Turkish expatriate sportspeople": "تصنيف:رياضيون أتراك مغتربون",
    "Category:Universiade medalists by sport": "تصنيف:فائزون بميداليات الألعاب الجامعية حسب الرياضة",
    "Category:Universiade medalists in water polo": "تصنيف:فائزون بميداليات الألعاب الجامعية في كرة الماء",
    "Category:Water polo at the Summer Universiade": "تصنيف:كرة الماء في الألعاب الجامعية الصيفية",
    "Category:Years in north korean television": "تصنيف:سنوات في التلفزة الكورية الشمالية",
    "Category:Youth athletics": "تصنيف:ألعاب القوى للشباب",
    "Category:Youth athletics competitions": "تصنيف:منافسات ألعاب قوى شبابية",
    "Category:Youth sports competitions": "تصنيف:منافسات رياضية شبابية",
    "Category:nations at the universiade": "تصنيف:بلدان في الألعاب الجامعية"
}

# ---
manga_list = {
    "Category:Action anime and manga": "تصنيف:أنمي ومانغا حركة",
    "Category:Adventure anime and manga": "تصنيف:أنمي ومانغا مغامرات",
    "Category:Apocalyptic anime and manga": "تصنيف:أنمي ومانغا نهاية العالم",
    "Category:Comedy anime and manga": "تصنيف:أنمي ومانغا كوميدية",
    "Category:Crime anime and manga": "تصنيف:أنمي ومانغا جريمة",
    "Category:Drama anime and manga": "تصنيف:أنمي ومانغا درامية",
    "Category:Dystopian anime and manga": "",
    "Category:Ecchi anime and manga": "",
    "Category:Fantasy anime and manga": "تصنيف:أنمي ومانغا فانتازيا",
    "Category:Harem anime and manga": "",
    "Category:Hentai anime and manga": "",
    "Category:Historical anime and manga": "تصنيف:أنمي ومانغا تاريخية",
    "Category:Horror anime and manga": "تصنيف:أنمي ومانغا رعب",
    "Category:Magical girl anime and manga": "تصنيف:أنمي ومانغا فتاة ساحرة",
    "Category:Martial arts anime and manga": "تصنيف:أنمي ومانغا فنون قتالية",
    "Category:Mecha anime and manga": "تصنيف:أنمي ميكا",
    "Category:Mystery anime and manga": "تصنيف:أنمي ومانغا غموض",
    "Category:Romance anime and manga": "تصنيف:أنمي ومانغا رومانسية",
    "Category:Science fiction anime and manga": "تصنيف:أنمي ومانغا خيال علمي",
    "Category:Slice of life anime and manga": "",
    "Category:Sports anime and manga": "تصنيف:أنمي ومانغا رياضية",
    "Category:Spy anime and manga": "تصنيف:أنمي ومانغا تجسسية",
    "Category:Superhero anime and manga": "تصنيف:أنمي ومانغا خارقة",
    "Category:Supernatural anime and manga": "تصنيف:أنمي ومانغا خارقة للطبيعة",
    "Category:Suspense anime and manga": "",
    "Category:Thriller anime and manga": "تصنيف:أنمي ومانغا إثارة",
    "Category:Tragedy anime and manga": "",
    "Category:War anime and manga": "تصنيف:أنمي ومانغا حربية",
    "Category:Western (genre) anime and manga": "",
    "Category:Yaoi anime and manga": "",
    "Category:Yuri (genre) anime and manga": ""
}

# ---
States_list = {
    "Category:African-American history by state": "تصنيف:تاريخ أمريكي إفريقي حسب الولاية",
    "Category:American Civil War by state navigational boxes": "تصنيف:صناديق تصفح الحرب الأهلية الأمريكية حسب الولاية",
    "Category:American culture by state": "تصنيف:ثقافة أمريكية حسب الولاية",
    "Category:Buildings and structures in the United States by state": "تصنيف:مبان ومنشآت في الولايات المتحدة حسب الولاية",
    "Category:Centuries in the United States by state": "تصنيف:قرون في الولايات المتحدة حسب الولاية",
    "Category:Communications in the United States by state": "تصنيف:الاتصالات في الولايات المتحدة حسب الولاية",
    "Category:Crimes in the United States by state": "تصنيف:جرائم في الولايات المتحدة حسب الولاية",
    "Category:Decades in the United States by state": "تصنيف:عقود في الولايات المتحدة حسب الولاية",
    "Category:Demographics of the United States by state": "تصنيف:التركيبة السكانية في الولايات المتحدة حسب الولاية",
    "Category:Disasters in the United States by state": "تصنيف:كوارث في الولايات المتحدة حسب الولاية",
    "Category:Economic history of the United States by state": "تصنيف:تاريخ الولايات المتحدة الاقتصادي حسب الولاية",
    "Category:Economy of the United States by state": "تصنيف:اقتصاد الولايات المتحدة حسب الولاية",
    "Category:Education in the United States by state": "تصنيف:التعليم في الولايات المتحدة حسب الولاية",
    "Category:Environment of the United States by state or territory": "تصنيف:بيئة الولايات المتحدة حسب الولاية أو الإقليم",
    "Category:Forts in the United States by state": "تصنيف:حصون في الولايات المتحدة حسب الولاية",
    "Category:Geography of the United States by state": "تصنيف:جغرافيا الولايات المتحدة حسب الولاية",
    "Category:Health in the United States by state": "تصنيف:الصحة في الولايات المتحدة حسب الولاية",
    "Category:Historians of U.S. states": "",
    "Category:Historic sites in the United States by state": "تصنيف:مواقع تاريخية في الولايات المتحدة حسب الولاية",
    "Category:Historic trails and roads in the United States by state": "تصنيف:طرق وممرات تاريخية في الولايات المتحدة حسب الولاية",
    "Category:History of the American Revolution by state": "تصنيف:تاريخ الثورة الأمريكية حسب الولاية",
    "Category:History of the United States by period by state": "تصنيف:تاريخ الولايات المتحدة حسب الحقبة حسب الولاية",
    "Category:History of the United States by state": "تصنيف:تاريخ الولايات المتحدة حسب الولاية",
    "Category:Images of the United States by state": "تصنيف:صور من الولايات المتحدة حسب الولاية",
    "Category:Labor relations in the United States by state": "",
    "Category:Landmarks in the United States by state": "تصنيف:معالم في الولايات المتحدة حسب الولاية",
    "Category:Legal history of the United States by state": "تصنيف:تاريخ الولايات المتحدة القانوني حسب الولاية",
    "Category:Manufacturing in the United States by state": "تصنيف:تصنيع في الولايات المتحدة حسب الولاية",
    "Category:Military history of the United States by state": "تصنيف:تاريخ الولايات المتحدة العسكري حسب الولاية",
    "Category:Native American history by state": "تصنيف:تاريخ الأمريكيين الأصليين حسب الولاية",
    "Category:Native American tribes by state": "تصنيف:قبائل أمريكية أصلية حسب الولاية",
    "Category:Nature reserves in the United States by state": "تصنيف:محميات طبيعية في الولايات المتحدة حسب الولاية",
    "Category:Outlines of U.S. states": "",
    "Category:People by state in the United States": "تصنيف:أشخاص حسب الولاية في الولايات المتحدة",
    "Category:Political history of the United States by state or territory": "تصنيف:تاريخ الولايات المتحدة السياسي حسب الولاية أو الإقليم",
    "Category:Politics of the United States by state": "تصنيف:سياسة الولايات المتحدة حسب الولاية",
    "Category:Pre-statehood history of U.S. states": "",
    "Category:Protected areas of the United States by state": "تصنيف:مناطق محمية في الولايات المتحدة حسب الولاية",
    "Category:Riots and civil disorder in the United States by state": "تصنيف:شغب وعصيان مدني في الولايات المتحدة حسب الولاية",
    "Category:Science and technology in the United States by state": "تصنيف:العلوم والتكنولوجيا في الولايات المتحدة حسب الولاية",
    "Category:Slavery in the United States by state": "تصنيف:العبودية في الولايات المتحدة حسب الولاية",
    "Category:Society of the United States by state": "تصنيف:مجتمع الولايات المتحدة حسب الولاية",
    "Category:Sports in the United States by state": "تصنيف:الرياضة في الولايات المتحدة حسب الولاية",
    "Category:State governments of the United States": "",
    "Category:State law in the United States": "",
    "Category:States of the United States history-related lists": "",
    "Category:States of the United States-related lists": "",
    "Category:Timelines of states of the United States": "",
    "Category:Tourist attractions in the United States by state": "تصنيف:مواقع جذب سياحي في الولايات المتحدة حسب الولاية",
    "Category:Transportation in the United States by state": "تصنيف:النقل في الولايات المتحدة حسب الولاية",
    "Category:United States historical societies by state": "",
    "Category:United States symbols by state": "",
    "Category:United States wars by state": "",
    "Category:Wildlife management areas by state": "",
    "Category:Years in the United States by state": "تصنيف:سنوات في الولايات المتحدة حسب الولاية"
}

# ---
States2_list = {
    "Category:Alabama": "تصنيف:ألاباما",
    "Category:Alaska": "تصنيف:ألاسكا",
    "Category:Arizona": "تصنيف:أريزونا",
    "Category:Arkansas": "تصنيف:أركنساس",
    "Category:California": "تصنيف:كاليفورنيا",
    "Category:Colorado": "تصنيف:كولورادو",
    "Category:Connecticut": "تصنيف:كونيتيكت",
    "Category:Delaware": "تصنيف:ديلاوير",
    "Category:Florida": "تصنيف:فلوريدا",
    "Category:Georgia (U.S. state)": "تصنيف:ولاية جورجيا",
    "Category:Hawaii": "تصنيف:هاواي",
    "Category:Idaho": "تصنيف:أيداهو",
    "Category:Illinois": "تصنيف:إلينوي",
    "Category:Indiana": "تصنيف:إنديانا",
    "Category:Iowa": "تصنيف:آيوا",
    "Category:Kansas": "تصنيف:كانساس",
    "Category:Kentucky": "تصنيف:كنتاكي",
    "Category:Louisiana": "تصنيف:لويزيانا",
    "Category:Maine": "تصنيف:مين",
    "Category:Maryland": "تصنيف:ماريلند",
    "Category:Massachusetts": "تصنيف:ماساتشوستس",
    "Category:Michigan": "تصنيف:ميشيغان",
    "Category:Minnesota": "تصنيف:مينيسوتا",
    "Category:Mississippi": "تصنيف:مسيسيبي",
    "Category:Missouri": "تصنيف:ميزوري",
    "Category:Montana": "تصنيف:مونتانا",
    "Category:Nebraska": "تصنيف:نبراسكا",
    "Category:Nevada": "تصنيف:نيفادا",
    "Category:New England states": "",
    "Category:New Hampshire": "تصنيف:نيوهامشير",
    "Category:New Jersey": "تصنيف:نيوجيرسي",
    "Category:New Mexico": "تصنيف:نيومكسيكو",
    "Category:New York (state)": "تصنيف:ولاية نيويورك",
    "Category:North Carolina": "تصنيف:كارولاينا الشمالية",
    "Category:North Dakota": "تصنيف:داكوتا الشمالية",
    "Category:Ohio": "تصنيف:أوهايو",
    "Category:Oklahoma": "تصنيف:أوكلاهوما",
    "Category:Oregon": "تصنيف:أوريغون",
    "Category:Pennsylvania": "تصنيف:بنسلفانيا",
    "Category:Rhode Island": "تصنيف:رود آيلاند",
    "Category:South Carolina": "تصنيف:كارولاينا الجنوبية",
    "Category:South Dakota": "تصنيف:داكوتا الجنوبية",
    "Category:Tennessee": "تصنيف:تينيسي",
    "Category:Texas": "تصنيف:تكساس",
    "Category:Utah": "تصنيف:يوتا",
    "Category:Vermont": "تصنيف:فيرمونت",
    "Category:Virginia": "تصنيف:فرجينيا",
    "Category:Washington (state)": "تصنيف:ولاية واشنطن",
    "Category:West Virginia": "تصنيف:فيرجينيا الغربية",
    "Category:Wisconsin": "تصنيف:ويسكونسن",
    "Category:Wyoming": "تصنيف:وايومنغ"
}


States3_list ={
    "Category:Buildings and structures in Westchester County, New York": "تصنيف:مبان ومنشآت في مقاطعة ويستتشستر (نيويورك)",
    "Category:Cemeteries in Westchester County, New York": "تصنيف:مقابر في مقاطعة ويستتشستر (نيويورك)",
    "Category:Christianity in Westchester County, New York": "تصنيف:المسيحية في مقاطعة ويستتشستر (نيويورك)",
    "Category:Churches in Westchester County, New York": "تصنيف:كنائس في مقاطعة ويستتشستر (نيويورك)",
    "Category:Companies based in Westchester County, New York": "تصنيف:شركات مقرها في مقاطعة ويستتشستر (نيويورك)",
    "Category:County routes in Westchester County, New York": "",
    "Category:Culture of Westchester County, New York": "تصنيف:ثقافة مقاطعة ويستتشستر (نيويورك)",
    "Category:Economy of Westchester County, New York": "تصنيف:اقتصاد مقاطعة ويستتشستر (نيويورك)",
    "Category:Education in Westchester County, New York": "تصنيف:التعليم في مقاطعة ويستتشستر (نيويورك)",
    "Category:Films set in Westchester County, New York": "تصنيف:أفلام تقع أحداثها في مقاطعة ويستتشستر (نيويورك)",
    "Category:Fire departments in Westchester County, New York": "",
    "Category:Geography of Westchester County, New York": "تصنيف:جغرافيا مقاطعة ويستتشستر (نيويورك)",
    "Category:Historic districts in Westchester County, New York": "تصنيف:المناطق التاريخية في مقاطعة ويستتشستر (نيويورك)",
    "Category:Hospitals in Westchester County, New York": "تصنيف:مستشفيات في مقاطعة ويستتشستر (نيويورك)",
    "Category:Houses in Westchester County, New York": "تصنيف:منازل في مقاطعة ويستتشستر (نيويورك)",
    "Category:Images of Westchester County, New York": "تصنيف:صور من مقاطعة ويستتشستر (نيويورك)",
    "Category:Landforms of Westchester County, New York": "تصنيف:تضاريس مقاطعة ويستتشستر (نيويورك)",
    "Category:Museums in Westchester County, New York": "تصنيف:متاحف في مقاطعة ويستتشستر (نيويورك)",
    "Category:National Register of Historic Places in Westchester County, New York": "تصنيف:السجل الوطني للأماكن التاريخية في مقاطعة ويستتشستر (نيويورك)",
    "Category:Parks in Westchester County, New York": "تصنيف:متنزهات في مقاطعة ويستتشستر (نيويورك)",
    "Category:People from Westchester County, New York": "تصنيف:أشخاص من مقاطعة ويستتشستر (نيويورك)",
    "Category:People from Westchester County, New York by city": "تصنيف:أشخاص من مقاطعة ويستتشستر (نيويورك) حسب المدينة",
    "Category:People from Westchester County, New York by hamlet": "تصنيف:أشخاص من مقاطعة ويستتشستر (نيويورك) حسب القرية",
    "Category:People from Westchester County, New York by town": "تصنيف:أشخاص من مقاطعة ويستتشستر (نيويورك) حسب البلدة",
    "Category:People from Westchester County, New York by village": "تصنيف:أشخاص من مقاطعة ويستتشستر (نيويورك) حسب القرية",
    "Category:Populated places in Westchester County, New York": "تصنيف:أماكن مأهولة في مقاطعة ويستتشستر (نيويورك)",
    "Category:Protected areas of Westchester County, New York": "تصنيف:مناطق محمية في مقاطعة ويستتشستر (نيويورك)",
    "Category:Schools in Westchester County, New York": "تصنيف:مدارس في مقاطعة ويستتشستر (نيويورك)",
    "Category:Sports in Westchester County, New York": "تصنيف:ألعاب رياضية في مقاطعة ويستتشستر (نيويورك)",
    "Category:Sports venues in Westchester County, New York": "تصنيف:ملاعب رياضية في مقاطعة ويستتشستر (نيويورك)",
    "Category:Sportspeople from Westchester County, New York": "تصنيف:رياضيون من مقاطعة ويستتشستر (نيويورك)",
    "Category:Streetcar lines in Westchester County, New York": "",
    "Category:Tourist attractions in Westchester County, New York": "تصنيف:مواقع جذب سياحي في مقاطعة ويستتشستر (نيويورك)",
    "Category:Transportation buildings and structures in Westchester County, New York": "تصنيف:مبان ومنشآت نقل في مقاطعة ويستتشستر (نيويورك)",
    "Category:Transportation in Westchester County, New York": "تصنيف:النقل في مقاطعة ويستتشستر (نيويورك)",
    "Category:Universities and colleges in Westchester County, New York": "تصنيف:جامعات وكليات في مقاطعة ويستتشستر (نيويورك)",
    "Category:Westchester County, New York politicians": ""
}
