name: deploy.yml
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          request_pty: true
          script_stop: true
          key: ${{ secrets.KEY }}
          script: |
            become ${{ secrets.TOOL1 }} bash -lc "
              shs/update_make2.sh &&
              echo \"Updated on: $(date '+%Y-%m-%d %H:%M:%S')\" > ~/update_make2_from_github
            "
            become ${{ secrets.TOOL2 }} bash -lc "
              web_sh/install_make2.sh ${{ secrets.GF_TOKEN }} &&
              echo \"Updated on: $(date '+%Y-%m-%d %H:%M:%S')\" > ~/update_make2_from_github &&
              webservice python3.11 restart
            "
